language: python
sudo: false
os:
  - linux

python:
  - "3.5"

env:
  - TOX_ENV=py35-dj19
  - TOX_ENV=py34-dj19
  - TOX_ENV=py27-dj19

matrix:
    fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
